#Payroll by Azura4k
#Requires LlamaEconomy and FormConstructor

#Money required to start a business
#This is required to subtract from a persons account.
IntialStartupCost: 5000

#Minimum Wage an employer can have.
MinimumWage: 10

#Tax Percent
TaxPercent : 0.0

#For every millisecond to check to see if a player needs force clockout
ForceClockOutInMilliseconds: 5000


#Here is all the Language Stuff
Language:

#Main Selection/Create Business Form - Starts with /Manage
  SelectFormTitle: 'Select A Business'
  CreateBusinessButton: 'Create Business'

#Create Business Form
  CreateBusinessFormTitle: 'Create A New Business'
  CreateBusinessFormNameLabel: 'Business Name'
  CreateBusinessFormDescriptionLabel: 'Business Description'
    #Startup Cost will always be at the end
  CreateBusinessFormStartupCost: 'Intial Cost: '

#Manage Business Info Form
  ManageBusinessInfoFormTitle: 'Manage Business - Change Details'
  ManageBusinessInfoFormBusinessName: 'Business Name'
  ManageBusinessInfoFormDesc: 'Business Description'
  ManageBusinessInfoFormMaxRank: 'Max Rank'
  ManageBusinessInfoFormMin: 'Min Rank'
  ManageBusinessInfoFormTrustedRank: 'Trusted Rank - Rank where players can Hire, Fire, and Manage Bank'
  ManageBusinessInfoFormUUID: 'Your Business UID: '

  #Note, Balance will be at the end
  ManageBusinessInfoFormBalance: 'Current Business Bank Balance is'
  ManageBusinessInfoFormTrustedRankBelowOwner: 'Current Trusted Rank: '
  ManageBusinessInfoFormNameBelowOwner: 'Business Name: '

#Delete Business Form
  DeleteBusinessFormTitle: 'Confirmation'
  #Business Name is at the end
  DeleteBusinessFormConfirmationText: 'Are you sure you wish to delete the following business? Once done, it cannot be reversed. Following Business Name is '
  DeleteBusinessFormYesButton: 'Yes'
  DeleteBusinessFormNoButton: 'No'
  DeleteBusinessFormAverted: 'Deletion Averted'

#Quit Job Form
  QuitJobFormTitle: 'Confirmation'
  QuitJobFormContent: 'Are you sure you want to quit? You will be leaving your position at: '
  QuitJobFormYesButton: 'Yes'
  QuitJobFormNoButton: 'No'

#Options Form
  OptionsFormBusinessInfoButton: 'Business Info'
  OptionsFormTreasuryButton: 'Treasury'
  OptionsFormEmployeeInfo: 'Employee Info'
  OptionsFormHireEmployees: 'Hire Employees'
  OptionsFormFireEmployees: 'Fire Employees'
  OptionsFormTransactions: 'Transactions'
  OptionsFormTransferOwner: 'Transfer Owner'
  OptionsFormQuitJob: 'Quit Job'
  OptionsFormDeleteBusiness: 'Delete Business'

#Bank Options Form
  BankOptionsFormTitle: 'Treasury'
  BankOptionsFormBalanceText: 'Current Balance Is: '
  BankOptionsFormDepositButton: 'Deposit'
  BankOptionsFormWithdrawButton: 'Withdraw'

#Deposit Form
  DepositFormTitle: 'Deposit Money'
  DepositFormEnterAmount: 'Please Enter the Amount of Money'
  DepositFormCurrentBalance: 'Current Balance is: '
  DepositFormButton: 'Deposit Money'
  #Amount comes after
  DepositFormSuccesful: 'Successfully Deposited: '

#Withdraw Form
  WithdrawFormTitle: 'Withdraw Money'
  WithdrawFormEnterAmount: 'Please Enter the Amount of Money'
  WithdrawFormCurrentBalance: 'Current Balance is: '
  WithdrawFormButton: 'Withdraw Money'
  WithdrawFormSuccesful: 'Successfully Withdrawn: '

# Errors and Codes
  BusinessNameAlrRegistered: 'Business Name is Already Taken'
  OverDraftRisk: 'Not Enough Money On Player'
  BusinessOverdraftRisk: 'Not Enough Money In Business'
  SuccessfullyUpdated: 'Information Successfully Updated'
  NoValueDetected: 'No Value Entered for'
  NoEmployeeFound: 'No Employee In this Business Found Under that Name'
  BackButton: 'Back'

#Employee Form
  EmployeeSelectionFormTitle: 'Select an Employee'
  EmployeeSelectionFormSearchButton: 'Search By Name'
  EmployeeSearchFormTitle: 'Search By Name'
  EmployeeSearchFormInstructions: 'Enter Player Name'

  EmployeeProfileFormTitle: 'Manage Employee'
  EmployeeProfileFormName: 'Employee Name: '
  EmployeeProfileFormStartDate: 'Start Date: '
  EmployeeProfileFormEmpTitle: 'Employee Title'
  EmployeeProfileFormRank: 'Employee Rank: '
  EmployeeProfileFormMaxMinutes: 'Maximum Minutes: '
  EmployeeProfileFormWage: 'Wage: '
  EmployeeProfileFormTotalMinutesWorked: 'Total Minutes Worked: '
  EmployeeProfileFormMinutesWorked: 'Minutes Worked: '
  EmployeeProfileFormIsFired: 'Is Fired: '
  EmployeeProfileFormDateFired: 'Fired on: '

  EmployeeSelectionFormManage: 'Manage'
  EmployeeSelectionFormTerm: 'Terminate'

#Hire and Fire
  HireTitle: 'Hire Employee'
  HirePlayerName: 'Player Name'
  HirePlayerTitle: 'Title'
  HirePlayerMaxMinutes: 'Max Minutes'
  HirePlayerRank: 'Rank'
  HirePlayerWage: 'Wage'
  HiringError: 'Error With Application, Once value was either Null or Not reaching minimum. Please Check Standards'


#JobOffer
  JobOfferMenuTitle: 'Job Offers'
  JobChoiceMenuTitle: 'Accept or Deny Position'
  JobChoiceMenuYesButton: 'Accept Position'
  JobChoiceMenuNoButton: 'Deny Position'

  JobChoiceContextBusinessName: 'Working for: '
  JobChoiceContextWage: 'Minutely Pay: '
  JobChoiceContextTitle: 'Position: '
  JobChoiceContextRank: 'Ranking: '
  JobChoiceContextMaxMinutes: 'Max Minutes: '

#QuitPosition Form
  QuitPositionFormContent: 'Are you sure you wish to quit your position at: '
  QuitPositionFormYes: 'Yes'
  QuitPositionFormNo: 'No'

#Transfer Ownership Form
  TransferOwnershipFormTitle: 'Transfer Ownership'
  TransferOwnershipTextBoxName: 'New Owner Name'

#EmployeeTermination
  EmployeeTerminationModalTitle: 'Termination'
  EmployeeTerminationModalContentPt1: 'Are you sure you want to terminate employment of '
  EmployeeTerminationModalContentPt2: ' with '
  EmployeeTerminationModalYesButton: 'Yes'
  EmployeeTerminationModalNoButton: 'No'
  EmployeeTerminationAbortionMessage: 'Aborted Termination of Player'

#ClockInClockOut
  ClockInButton: 'Clock In'
  ClouckOutButton: 'Clock Out'
  CurrentPayMinutes: 'Minutes for this period: '
  ClockInJobSelectFormTitle: 'Select A Timecard'
  PayoutOutButton: 'Pay Out'